/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.mbse.mbtimes.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractNplValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.tu_bs.cs.isf.mbse.mbtimes.npl.NplPackage.eINSTANCE);
		return result;
	}
}
