/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.mbse.mbtimes.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class NplUiModule extends de.tu_bs.cs.isf.mbse.mbtimes.ui.AbstractNplUiModule {
	public NplUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
