/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.mbse.mbtimes.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class NplAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/tu_bs/cs/isf/mbse/mbtimes/parser/antlr/internal/InternalNpl.tokens");
	}
}
