/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.mbse.mbtimes;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class NplUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return de.tu_bs.cs.isf.mbse.mbtimes.ui.internal.NplActivator.getInstance().getInjector("de.tu_bs.cs.isf.mbse.mbtimes.Npl");
	}
	
}
