/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.mbse.mbtimes;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NplRuntimeModule extends de.tu_bs.cs.isf.mbse.mbtimes.AbstractNplRuntimeModule {

}
