/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.mbse.mbtimes.ui.contentassist

import de.tu_bs.cs.isf.mbse.mbtimes.ui.contentassist.AbstractNplProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class NplProposalProvider extends AbstractNplProposalProvider {
}
