/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.mbse.mbtimes.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.tu_bs.cs.isf.mbse.mbtimes.ui.internal.NplActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class NplExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return NplActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return NplActivator.getInstance().getInjector(NplActivator.DE_TU_BS_CS_ISF_MBSE_MBTIMES_NPL);
	}
	
}
